project:
  type: website

website:
  title: "Against the Gods"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/charlie-arturo-do-amaral-becerra/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

