project:
  type: website

website:
  title: "Contra los dioses"
  favicon: "images/profile.jpg"
  google-analytics: "G-7NN6VFNJH3"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Proyectos
        href: proyectos.qmd
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/charlie-arturo-do-amaral-becerra/
      - icon: youtube
        href: https://www.youtube.com/@Estadistiqueando
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

